name: Run Tests for gcd.sh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set execute permissions
      run: |
        chmod +x gcd.sh
        chmod +x gcd_test.sh

    - name: Run Test Script
      run: ./gcd_test.sh
